src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Contact::class, mappedBy="user_id", orphanRemoval=true)
     */
    private $contacts;

    /**
     * @ORM\OneToMany(targetEntity=Invoice::class, mappedBy="user", orphanRemoval=true)
     */
    private $invoices;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $company_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $addr_street;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $addr_city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $vat_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $bank_account_number;


    public function __construct()
    {
        $this->contacts = new ArrayCollection();
        $this->invoices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection|Contact[]
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts[] = $contact;
            $contact->setUserId($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contacts->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getUserId() === $this) {
                $contact->setUserId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Invoice[]
     */
    public function getInvoices(): Collection
    {
        return $this->invoices;
    }

    public function addInvoice(Invoice $invoice): self
    {
        if (!$this->invoices->contains($invoice)) {
            $this->invoices[] = $invoice;
            $invoice->setUser($this);
        }

        return $this;
    }

    public function removeInvoice(Invoice $invoice): self
    {
        if ($this->invoices->removeElement($invoice)) {
            // set the owning side to null (unless already changed)
            if ($invoice->getUser() === $this) {
                $invoice->setUser(null);
            }
        }

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getCompanyName(): ?string
    {
        return $this->company_name;
    }

    public function setCompanyName(?string $company_name): self
    {
        $this->company_name = $company_name;

        return $this;
    }

    public function getAddrStreet(): ?string
    {
        return $this->addr_street;
    }

    public function setAddrStreet(?string $addr_street): self
    {
        $this->addr_street = $addr_street;

        return $this;
    }

    public function getAddrCity(): ?string
    {
        return $this->addr_city;
    }

    public function setAddrCity(?string $addr_city): self
    {
        $this->addr_city = $addr_city;

        return $this;
    }

    public function getVatNumber(): ?string
    {
        return $this->vat_number;
    }

    public function setVatNumber(?string $vat_number): self
    {
        $this->vat_number = $vat_number;

        return $this;
    }

    public function getBankAccountNumber(): ?string
    {
        return $this->bank_account_number;
    }

    public function setBankAccountNumber(?string $bank_account_number): self
    {
        $this->bank_account_number = $bank_account_number;

        return $this;
    }

}

templates/app/index.html.twig
{% extends 'layout.html.twig' %}

{% block body %}
{#    <div class="row">#}
{#        <div class="col-12" style="background-color:#212529; color: white; text-align: center; padding: 20px; margin-top: 20px">#}
{#            <div class="col-2 offset-5" style="border-top: 1px solid rgba(255,255,255,.55)"><h1>Můj účet</h1></div>#}
{#        </div>#}
{#    </div>#}

{#    <style>#}
{#        td {#}
{#            border: 1px solid#}
{#        }#}
{#    </style>#}
    <div class="row">
        <div class="col-6" style="padding: 20px">
            <table class="table">
                <thead>
                    <th style="font-size: 18px;">Účet:</th>
                    <th style="text-align: right">
                        <div class="btn btn-primary btn-sm">Upravit údaje</div>
                        <div class="btn btn-primary btn-sm">Změnit heslo</div>
                        <div class="btn btn-danger btn-sm">Odstranit účet</div>
                    </th>
                </thead>
                <tbody>
                <tr>
                    <th scope="row">Email:</th>
                    <td>{{ app.user.email }}</td>
                </tr>
                <tr>
                    <th scope="row">Jméno:</th>
                    <td>{{ app.user.firstName }}</td>
                </tr>
                <tr>
                    <th scope="row">Příjmení:</th>
                    <td>{{ app.user.lastName }}</td>
                </tr>
                <tr>
                    <th scope="row">Název firmy:</th>
                    <td>{{ app.user.companyName }}</td>
                </tr>
                <tr>
                    <th scope="row">Ičo:</th>
                    <td>{{ app.user.vatNumber }}</td>
                </tr>
                <tr>
                    <th scope="row">Číslo účtu:</th>
                    <td>{{ app.user.bankAccountNumber }}</td>
                </tr>
                <tr>
                    <th scope="row">Město:</th>
                    <td>{{ app.user.addrCity }}</td>
                </tr>
                <tr>
                    <th scope="row">Ulice:</th>
                    <td>{{ app.user.addrStreet }}</td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-6" style="padding: 20px">
            <table class="table">
                <thead>
                <th style="font-size: 18px;">Statistiky:</th>
                </thead>
                <tbody>
                <tr>
                    <th scope="row">Registrován:</th>
                    <td>{{ app.user.firstName }}</td>
                </tr>
                <tr>
                    <th scope="row">Kontaktů v adresáři:</th>
                    <td>{{ app.user.email }}</td>
                </tr>
                <tr>
                    <th scope="row">Vydaných faktur:</th>
                    <td>{{ app.user.lastName }}</td>
                </tr>
                <tr>
                    <th scope="row">Vydané faktury částka:</th>
                    <td>{{ app.user.lastName }}</td>
                </tr>
                <tr>
                    <th scope="row">Přijatých faktur:</th>
                    <td>{{ app.user.companyName }}</td>
                </tr>
                <tr>
                    <th scope="row">Přijaté faktury částka:</th>
                    <td colspan="2">{{ app.user.lastName }}</td>
                </tr>
                <tr>
                    <th scope="row">Nezaplacené faktury:</th>
                    <td>{{ app.user.vatNumber }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-4" style="">
            Prejdete na preium
        </div>
        <div class="col-4" style="text-align: center">
            <img src="http://pngimg.com/uploads/free/free_PNG90769.png" width="300" height="300" />
            <div class="row">
                <div class="col">
                    Vyhoda
                </div>
            </div>
        </div>
        <div class="col-4" style="text-align: center">
            <img src="https://thumbs.dreamstime.com/b/premium-seal-eps-16109419.jpg" width="300" height="300" />
            <div class="row">
                <div class="col">
                    Vyhoda
                </div>
            </div>
        </div>
    </div>
{% endblock %}