src/Entity/Invoice.php
<?php

namespace App\Entity;

use App\Repository\InvoiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InvoiceRepository::class)
 */
class Invoice
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $invoice_number;


    /**
     * @ORM\ManyToOne(targetEntity=Contact::class, inversedBy="invoices",cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $contact;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $variable_symbol;

    /**
     * @ORM\ManyToOne(targetEntity=Payment::class, inversedBy="invoices")
     * @ORM\JoinColumn(nullable=false)
     */
    private $payment_method;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $text_before;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $text_after;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $note;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $footer_text;

    /**
     * @ORM\ManyToOne(targetEntity=InvoiceType::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $invoice_type;

    /**
     * @ORM\ManyToOne(targetEntity=InvoiceAccountingType::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $InvoiceAccountingType;

    /**
     * @ORM\Column(type="date")
     */
    private $create_date;

    /**
     * @ORM\Column(type="date")
     */
    private $due_date;

    /**
     * @ORM\Column(type="date")
     */
    private $tax_application_date;

    /**
     * @ORM\ManyToOne(targetEntity=InvoiceStatus::class, inversedBy="invoices")
     * @ORM\JoinColumn(nullable=false)
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="invoices")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Currency::class, inversedBy="invoices")
     * @ORM\JoinColumn(nullable=false)
     */
    private $currency;

    /**
     * @ORM\OneToMany(targetEntity=InvoiceItem::class, mappedBy="invoice", orphanRemoval=true, cascade={"persist"})
     */
    private $invoiceItems;

    /**
     * @ORM\Column(type="float")
     */
    private $price;


    public function __construct()
    {
        $this->invoice_item_id = new ArrayCollection();
        $this->invoiceItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInvoiceNumber(): ?string
    {
        return $this->invoice_number;
    }

    public function setInvoiceNumber(string $invoice_number): self
    {
        $this->invoice_number = $invoice_number;

        return $this;
    }


    public function getContact(): ?Contact
    {
        return $this->contact;
    }

    public function setContact(?Contact $contact): self
    {
        $this->contact = $contact;

        return $this;
    }

    public function getVariableSymbol(): ?string
    {
        return $this->variable_symbol;
    }

    public function setVariableSymbol(string $variable_symbol): self
    {
        $this->variable_symbol = $variable_symbol;

        return $this;
    }

    public function getPaymentMethod(): ?Payment
    {
        return $this->payment_method;
    }

    public function setPaymentMethod(?Payment $payment_method): self
    {
        $this->payment_method = $payment_method;

        return $this;
    }

    public function getTextBefore(): ?string
    {
        return $this->text_before;
    }

    public function setTextBefore(?string $text_before): self
    {
        $this->text_before = $text_before;

        return $this;
    }

    public function getTextAfter(): ?string
    {
        return $this->text_after;
    }

    public function setTextAfter(?string $text_after): self
    {
        $this->text_after = $text_after;

        return $this;
    }


    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getFooterText(): ?string
    {
        return $this->footer_text;
    }

    public function setFooterText(?string $footer_text): self
    {
        $this->footer_text = $footer_text;

        return $this;
    }

    public function getInvoiceType(): ?InvoiceType
    {
        return $this->invoice_type;
    }

    public function setInvoiceType(?InvoiceType $invoice_type): self
    {
        $this->invoice_type = $invoice_type;

        return $this;
    }

    public function getInvoiceAccountingType(): ?InvoiceAccountingType
    {
        return $this->InvoiceAccountingType;
    }

    public function setInvoiceAccountingType(?InvoiceAccountingType $InvoiceAccountingType): self
    {
        $this->InvoiceAccountingType = $InvoiceAccountingType;

        return $this;
    }

    public function getCreateDate(): ?\DateTimeInterface
    {
        return $this->create_date;
    }

    public function setCreateDate(\DateTimeInterface $create_date): self
    {
        $this->create_date = $create_date;

        return $this;
    }

    public function getDueDate(): ?\DateTimeInterface
    {
        return $this->due_date;
    }

    public function setDueDate(\DateTimeInterface $due_date): self
    {
        $this->due_date = $due_date;

        return $this;
    }

    public function getTaxApplicationDate(): ?\DateTimeInterface
    {
        return $this->tax_application_date;
    }

    public function setTaxApplicationDate(\DateTimeInterface $tax_application_date): self
    {
        $this->tax_application_date = $tax_application_date;

        return $this;
    }

    public function getStatus(): ?InvoiceStatus
    {
        return $this->status;
    }

    public function setStatus(?InvoiceStatus $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCurrency(): ?Currency
    {
        return $this->currency;
    }

    public function setCurrency(?Currency $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    /**
     * @return Collection|InvoiceItem[]
     */
    public function getInvoiceItems(): Collection
    {
        return $this->invoiceItems;
    }

    public function addInvoiceItem(InvoiceItem $invoiceItem): self
    {
        if (!$this->invoiceItems->contains($invoiceItem)) {
            $this->invoiceItems[] = $invoiceItem;
            $invoiceItem->setInvoice($this);
        }

        return $this;
    }

    public function removeInvoiceItem(InvoiceItem $invoiceItem): self
    {
        if ($this->invoiceItems->removeElement($invoiceItem)) {
            // set the owning side to null (unless already changed)
            if ($invoiceItem->getInvoice() === $this) {
                $invoiceItem->setInvoice(null);
            }
        }

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

}

src/Entity/InvoiceStatus.php
<?php

namespace App\Entity;

use App\Repository\InvoiceStatusRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InvoiceStatusRepository::class)
 */
class InvoiceStatus
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status_name;

    /**
     * @ORM\OneToMany(targetEntity=Invoice::class, mappedBy="status")
     */
    private $invoices;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isDefault;

    public function __construct()
    {
        $this->invoices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatusName(): ?string
    {
        return $this->status_name;
    }

    public function setStatusName(string $status_name): self
    {
        $this->status_name = $status_name;

        return $this;
    }

    /**
     * @return Collection|Invoice[]
     */
    public function getInvoices(): Collection
    {
        return $this->invoices;
    }

    public function addInvoice(Invoice $invoice): self
    {
        if (!$this->invoices->contains($invoice)) {
            $this->invoices[] = $invoice;
            $invoice->setStatus($this);
        }

        return $this;
    }

    public function removeInvoice(Invoice $invoice): self
    {
        if ($this->invoices->removeElement($invoice)) {
            // set the owning side to null (unless already changed)
            if ($invoice->getStatus() === $this) {
                $invoice->setStatus(null);
            }
        }

        return $this;
    }

    public function getIsDefault(): ?bool
    {
        return $this->isDefault;
    }

    public function setIsDefault(?bool $isDefault): self
    {
        $this->isDefault = $isDefault;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Contact::class, mappedBy="user_id", orphanRemoval=true)
     */
    private $contacts;

    /**
     * @ORM\OneToMany(targetEntity=Invoice::class, mappedBy="user", orphanRemoval=true)
     */
    private $invoices;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $company_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $addr_street;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $addr_city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $vat_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $bank_account_number;


    public function __construct()
    {
        $this->contacts = new ArrayCollection();
        $this->invoices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection|Contact[]
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts[] = $contact;
            $contact->setUserId($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contacts->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getUserId() === $this) {
                $contact->setUserId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Invoice[]
     */
    public function getInvoices(): Collection
    {
        return $this->invoices;
    }

    public function addInvoice(Invoice $invoice): self
    {
        if (!$this->invoices->contains($invoice)) {
            $this->invoices[] = $invoice;
            $invoice->setUser($this);
        }

        return $this;
    }

    public function removeInvoice(Invoice $invoice): self
    {
        if ($this->invoices->removeElement($invoice)) {
            // set the owning side to null (unless already changed)
            if ($invoice->getUser() === $this) {
                $invoice->setUser(null);
            }
        }

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getCompanyName(): ?string
    {
        return $this->company_name;
    }

    public function setCompanyName(?string $company_name): self
    {
        $this->company_name = $company_name;

        return $this;
    }

    public function getAddrStreet(): ?string
    {
        return $this->addr_street;
    }

    public function setAddrStreet(?string $addr_street): self
    {
        $this->addr_street = $addr_street;

        return $this;
    }

    public function getAddrCity(): ?string
    {
        return $this->addr_city;
    }

    public function setAddrCity(?string $addr_city): self
    {
        $this->addr_city = $addr_city;

        return $this;
    }

    public function getVatNumber(): ?string
    {
        return $this->vat_number;
    }

    public function setVatNumber(?string $vat_number): self
    {
        $this->vat_number = $vat_number;

        return $this;
    }

    public function getBankAccountNumber(): ?string
    {
        return $this->bank_account_number;
    }

    public function setBankAccountNumber(?string $bank_account_number): self
    {
        $this->bank_account_number = $bank_account_number;

        return $this;
    }

}

templates/invoices/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Hello ContactsController!{% endblock %}

{% block body %}
    <div class="main">
        <div class="container">
            <h1 class="h1">Editace kontaktu</h1>
            {{ form(form) }}
        </div>
    </div>

{% endblock %}

templates/invoices/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Hello ContactsController!{% endblock %}


{% block body %}
    <div class="main">
        <div class="container">
            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
            <a href="{{ path('invoices.create') }}">
                <button type="button" class="btn btn-secondary btn-lg btn-block" style="margin-top: 20px">
                    Nový doklad<i class="fas fa-user-plus" style="padding-left: 10px"></i>
                </button>
            </a>

            <table class="table table-striped" style="margin-top: 30px">
                <thead>
                <tr>
                    <th>Číslo</th>
                    <th>Typ</th>
                    <th>Firma/Kontakt</th>
                    <th>Vystaveno</th>
                    <th>Splatnost</th>
                    <th>Stav</th>
                    <th>Akce</th>
                </tr>
                </thead>
                <tbody>
                {% for invoice in invoices %}
                    <tr>
                        <td>{{ invoice.invoiceNumber }}</td>
                        <td>{{ invoice.invoiceType.TypeName }}</td>
                        <td>{{ invoice.contact.title }}</td>
                        <td>{{ invoice.createDate|date('d-m-Y') }}</td>
                        <td>{{ invoice.dueDate|date('d-m-Y') }}</td>
                        <td>{{ invoice.status.statusName }}</td>
                        <td>
                            <a href="{{ path('invoices.remove', {id: invoice.id}) }}"><i class="far fa-trash-alt" data-toggle="tooltip" data-placement="top" title="Odstranit doklad"></i></a>
                            <a href="{{ path('invoices.edit', {id: invoice.id}) }}"><i class="fas fa-edit" data-toggle="tooltip" data-placement="top" title="TO DO - Editovat doklad"></i></a>
                            <a href="{{ path('invoices.generate', {id: invoice.id}) }}"><i class="fas fa-file-pdf" data-toggle="tooltip" data-placement="top" title="Generovat PDF"></i></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

templates/invoices/invoice.html.twig
{% block stylesheets %}
    <link href="{{ asset('/css/styles.css') }}" rel="stylesheet">
    <link href="{{ asset('/css/sidebars.css') }}" rel="stylesheet">
    <link href="{{ asset('/css/fontawesome-all.css') }}" rel="stylesheet">

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
        }
        table {
            /*border: 1px solid gray;*/
            font-size: 12px;
            max-width: 2480px;
            width:100%;
            border-collapse: collapse;
        }
        table, td {
            /*border: 1px solid gray;*/
            min-height: 10px;
            padding: 5px;
        }

        .t-head {
            font-size: 14px;
        }

        .final-price {
            font-size: 14px;
            text-align: right;
            margin-top: 5px;
            padding-top: 5px;
            border-top: 1px solid black;
        }
        .final-price .price {
            font-weight: bold;
            display: block;
            font-size: 18px;
            margin-block-start: 0.3em !important;
            margin-right: 2px;
        }

        .invoice-number {
            text-align: right;

        }
        .invoice-number .number {
            font-weight: bold;
            font-size: 19px;
        }

        .qr-code {
            /*vertical-align: top;*/
            /*display: inline-block;*/
            /*text-align: center;*/
        }
        .qr-code {
            display: block;
            padding-right: 50px;
            color: gray;
            font-size: 10px;
            font-style: italic;
            margin-top: -50px;
            /*display: block;*/
        }


        .content {
            width: 100%;
            max-width: 210mm;
            /*border: 2px solid green;*/
        }
        .column-10 {
            width: 100%;
        }
        .column-9 {
            width: 90%;
        }
        .column-8 {
            width: 80%;
        }
        .column-7 {
            width: 70%;
        }
        .column-6 {
            width: 60%;
        }
        .column-5 {
            width: 50%;
        }
        .column-4 {
            width: 40%;
        }
        .column-3 {
            width: 30%;
        }
        .column-2 {
            width: 20%;
        }
        .column-1 {
            width: 10%;
        }
        /*td {*/
        /*    border: 1px solid black;*/
        /*}*/

    </style>

{% endblock %}

    {% block javascripts %}

    {% endblock %}

{% block body %}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
     <body>
     <div class="content">
         <table>
             <tr>
                 <td class="column-5" rowspan="3" style="text-align: center">Logo </td>
                 <td class="column-5 invoice-number">
                     <div class="number">Faktura č. {{ invoice.invoiceNumber }}</div>

                 </td>
             </tr>
             <tr>
                 <td></td>
             </tr>
             <tr>
                 <td></td>
             </tr>

         </table>
         <table style="margin-top: 1em">
             <tr>
                 <th class="column-5 t-head" style="text-align: left">Dodavatel</th>
                 <th class="column-5 t-head" style="text-align: right">Odběratel</th>
             </tr>
             <tr>
                 {% if user.firstName is defined and user.firstName is not null %}
                     <td>{{ user.firstName }}</td>
                 {% else %}
                     <td></td>
                 {% endif %}

                 {% if invoice.contact.firstName is defined and invoice.contact.firstName is not null %}
                     <td style="text-align: right">{{ invoice.contact.firstName }}</td>
                 {% else %}
                     <td></td>
                 {% endif %}
             </tr>
             <tr>
                 {% if user.companyName is defined and user.companyName is not null %}
                     <td>{{ user.companyName }}</td>
                 {% else %}
                     <td></td>
                 {% endif %}

                 {% if invoice.contact.title is defined and invoice.contact.title is not null %}
                     <td style="text-align: right">{{ invoice.contact.title }}</td>
                 {% else %}
                     <td></td>
                 {% endif %}
             </tr>
             <tr>
                 {% if user.addrStreet is defined and user.addrStreet is not null %}
                     <td>{{ user.addrStreet }}</td>
                 {% else %}
                     <td></td>
                 {% endif %}

                 {% if invoice.contact.addrStreet is defined and invoice.contact.addrStreet is not null %}
                     <td style="text-align: right">{{ invoice.contact.addrStreet }}</td>
                 {% else %}
                     <td></td>
                 {% endif %}
             </tr>
             <tr>
                 {% if user.addrCity is defined and user.addrCity is not null %}
                     <td>{{ user.addrCity }}</td>
                 {% else %}
                     <td></td>
                 {% endif %}

                 {% if invoice.contact.addrCity is defined and invoice.contact.addrCity is not null %}
                     <td style="text-align: right">{{ invoice.contact.addrCity }}</td>
                 {% else %}
                     <td></td>
                 {% endif %}
             </tr>
             <tr>
                 {% if user.vatNumber is defined and user.vatNumber is not null %}
                     <td>IČO: {{ user.vatNumber }}</td>
                 {% else %}
                     <td></td>
                 {% endif %}

                 {% if invoice.contact.vatNumber is defined and invoice.contact.vatNumber is not null %}
                     <td style="text-align: right">IČO: {{ invoice.contact.vatNumber }}</td>
                 {% else %}
                     <td></td>
                 {% endif %}
             </tr>
             <tr style="height: 14px;">
                 {% if user.bankAccountNumber is defined and user.bankAccountNumber is not null %}
                     <td>Bankovní spojení: {{ user.bankAccountNumber }}</td>
                 {% else %}
                     <td></td>
                 {% endif %}
                 <td style="text-align: right; padding: 0" rowspan="5">
                         <img src="https://chart.googleapis.com/chart?chs=150x150&cht=qr&chl=SPD*1.0*ACC:CZ2806000000000168540115*AM:450.00*CC:CZK*MSG:PLATBA%20ZA%20ZBOZI*X-VS:1234567890" />
                 </td>
             </tr>
             <tr style="height: 14px;">
                 {% if invoice.variableSymbol is defined and invoice.variableSymbol is not null %}
                     <td>Variabilní symbol: {{ invoice.variableSymbol }}</td>
                 {% else %}
                     <td></td>
                 {% endif %}
             </tr>
             <tr><td></td></tr>
             <tr><td></td></tr>
             <tr><td></td>
             </tr>
             <tr>
                 <td></td>
                 <td class="qr-code" style="text-align: right; padding-right: 25px;"> Platba pomocí qr kódu</td>
             </tr>
         </table>
         {% if invoice.textBefore is defined and invoice.textBefore is not null %}
             <div class="text-before" style="overflow: hidden; height: 75px; padding-top: 1em">
                 {{ invoice.textBefore }}
             </div>
         {% endif %}

         <table style="margin-top: 1em">
             <tr>
                 <th class="t-head" style="text-align: left; padding: 1em">Položky</th>
             </tr>
             <tr style="border-bottom: 1px solid gray">
                 <th class="column-4" style="text-align: left">Název</th>
                 <th class="column-1">Množství</th>
                 <th class="column-1">Jednotka</th>
                 <th class="column-2">Jednotková cena</th>
                 <th class="column-2" style="text-align: right">Celkem</th>
             </tr>
             {% for invoiceItem in invoice.invoiceItems %}
                 <tr style="padding: 2px">
                     <td class="column-4" style="text-align: left"> {{ invoiceItem.name }}</td>
                     <td class="column-1" style="text-align: center">{{ invoiceItem.amount }}</td>
                     <td class="column-1" style="text-align: center">{{ invoiceItem.unit }}</td>
                     <td class="column-2" style="text-align: center">{{ invoiceItem.pricePerUnit }}</td>
                     <td class="column-2" style="text-align: right">{{ invoiceItem.price }}</td>
                 </tr>
             {% endfor %}
         </table>

         <div class="final-price">
             {% if invoice.price is defined and invoice.price is not null %}
                   Celková cena: <div class="price">{{ invoice.price }} {% if invoice.currency.name is defined and invoice.currency.name is not null %} {{ invoice.currency.name }} {% endif %}</div>
             {% endif %}
         </div>


         {% if invoice.textAfter is defined and invoice.textAfter is not null %}
             <div class="text-after" style="overflow: hidden; height: 75px; padding-top: 1em">
                 {{ invoice.textAfter }}
             </div>
         {% endif %}

         {% if invoice.note is defined and invoice.note is not null %}
             <div class="text-note" style="overflow: hidden; height: 75px; padding-top: 1em; text-align: center">
                 {{ invoice.note }}
             </div>
         {% endif %}

         {% if invoice.footerText is defined and invoice.footerText is not null %}
             <div class="text-footer" style="overflow: hidden; height: 75px; padding-top: 1em">
                 {{ invoice.footerText }}
             </div>
         {% endif %}
     </div>

    </body>



{% endblock %}